Repository riscv-software-src/riscv-perf-model, pull requests merged in 2023-12, with the labels that each got.

#120 Ignore Renaming of x0
  core/Inst.hpp
  core/LSU.cpp
  core/Rename.cpp
  test/core/rename/Rename_test.cpp
  test/core/rename/expected_output/big_core.out.EXPECTED
  test/core/rename/expected_output/big_core_small_rename.out.EXPECTED
  test/core/rename/expected_output/medium_core.out.EXPECTED
  test/core/rename/expected_output/small_core.out.EXPECTED
Labels: enhancement

#129 Fixed clang compilation issues
  mss/L2Cache.cpp
  test/core/l2cache/L2Cache_test.cpp
  test/core/l2cache/L2SourceUnit.hpp
Labels: bug

#108 Raise exception in LSU when ROB is drained
  core/Fetch.hpp
  core/Inst.hpp
  core/InstGenerator.cpp
  core/LSU.cpp
  core/LSU.hpp
  core/ROB.cpp
  core/ROB.hpp
  test/core/rename/Rename_test.cpp
Labels: bug, enhancement
